on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-debugger:latest
          build-args: --attest type=provenance,mode=max --sbom=true
      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ secrets.DOCKERHUB_USERNAME }}/docker-debugger
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true